version: "3.8"
services:
 redis:
   image: "redis:alpine"
   command: redis-server /usr/local/etc/redis/redis.conf
   ports:
    - "6379:6379"
   volumes:
    - $PWD/redis-data:/var/lib/redis
    - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
 queue:
   # image: "103425057857.dkr.ecr.us-west-2.amazonaws.com/jitsi-vo/jibri-queue:0.0.3"
   build: ../.
   ports:
    - "8080:8080"
   environment:
    - LOG_LEVEL=debug
    - PROTECTED_API=true
    - REDIS_HOST=redis
    - REDIS_PASSWORD=demopw
    - ASAP_PUB_KEY_BASE_URL=https://d4dv7jmo5uq1d.cloudfront.net/server/stage
    - ASAP_JWT_ISS=jibri-queue
    - ASAP_JWT_KID=jibri-queue-pilot-20200805
    - ASAP_JWT_AUD=jitsi
    - ASAP_JWT_ACCEPTED_AUD=jibri-queue
    - ASAP_JWT_ACCEPTED_ISS=jitsi
    - ASAP_JWT_ACCEPTED_HOOK_ISS=jibri
    - TOKEN_SIGNING_KEY_FILE=/usr/local/private.pem
    - REDIS_TLS_ENABLED=false
   volumes:
    - $PWD/private.pem:/usr/local/private.pem
